[project]
name = "tracking-no"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=37.4.2",
    "gspread>=6.2.1",
    "streamlit>=1.47.0",
]
